version: 2.1
orbs:
  architect: giantswarm/architect@4.26.0

workflows:
  build-workflow:
    jobs:

      - architect/push-to-docker:
          context: "architect"
          name: "push-signcode-util-to-quay"
          image: "quay.io/giantswarm/signcode-util"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          build-context: "."
          dockerfile: "./Dockerfile"
          tag-suffix: ""
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
