version: 2.1
orbs:
  architect: giantswarm/architect@4.37.0

workflows:
  build-workflow:
    jobs:

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
